  
version: '3.7'

services:
  api:
    container_name: fau-cen5035-demo-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3001

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret